### ISSUE TITLE
Broken link in Docs

### ISSUE THREAD

**Issue by tajmone** [TryKickoff/kickoff#78]
In Yeoman page:

http://trykickoff.com/learn/yeoman.html

point 7 of the list (`Use Kickoff Statix for static templating and rapid prototyping?`)

Link to Statix points to a "page not found":

http://trykickoff.com/kickoff/statix/

I've managed to reach the Statix page only out of context:

http://trykickoff.com/statix/

**Comment by ashleynolan** [comment]
@tajmone Thanks for raising this – has now been fixed in [this commit](https://github.com/TryKickoff/trykickoff.github.io/commit/8e5ddf7e8a59ff571ebd118a8059a14fa5192e88).

I’ve pointed it to the Statix Github repo for now as the docs are currently being restyled (along with documentation updates to Kickoff’s docs for the upcoming v7).
