### ISSUE TITLE
IE11 Printing Issue

### ISSUE THREAD

**Issue by denzBrade** [TryKickoff/kickoff#92]
In the print styles:

```
@media print {
	*,
	*:before,
	*:after,
	*:first-letter {
	*:first-line { REMOVE THIS LINE to avoid Printing Issues with IE11 (not supported)
}
```

Crashes IE 11 Print preview & blocks IE11 from printing at all

**Comment by mrmartineau** [comment]
@denz-brade-2015 so this fixes the bug you've been trying to fix recently? It is strange that this is the solution because the base for Kickoff's print styles comes directly from [the HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/3855f43e7269dd910a76bd18d8b3bb7a51c8084d/src/css/main.css#L203), which still has that line in there.. I am happy to remove this. Fancy submitting a pull request with the change? ;)

**Comment by mrmartineau** [comment]
For reference, [this is the commit when it was added to Kickoff](https://github.com/TryKickoff/kickoff/commit/b792362faffa92d6cc44537d86e278b7ebe608d3) (from September last year) and [this is the commit when it was added to H5BP](https://github.com/h5bp/html5-boilerplate/commit/fc05bc82abf26f4042c86a17652dd232362f78ad)
